In [96]:
import numpy as np

In [97]:
a=np.array([[[0,1],[2,3]],[[5,6],[7,8]]])
a.shape
a[1,1,0]

t=np.dtype([('name', str, 40), ('numitems', np.int32), ('price',np.float32)])
t['numitems']

dtype('int32')

In [98]:
s=np.array([('DOG',32,12.8),('cat',56,45.8)],dtype=t)
s

array([('DOG', 32,  12.80000019), ('cat', 56,  45.79999924)], 
      dtype=[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [99]:
b=np.arange(24).reshape(2,3,2,2)
b

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [100]:
b[-1,:,-1]

array([[14, 15],
       [18, 19],
       [22, 23]])

- 张量bijkl，显示时是从后向前，依次递增下标的，如：
b0000,b0001;b0010,b0011;
b0100,b0101;b0110;b0111;...
- 转置:aij=bji,sjikl=tijkl=t(1,0)

In [101]:
c=b.ravel()
c[0]=-1

In [102]:
d=b.flatten()
d[0]=-2

In [103]:
e=b.transpose()
e

array([[[[-1, 12],
         [ 4, 16],
         [ 8, 20]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]]],


       [[[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]]]])